import React from 'react'

export default function TermsPage() {
  return (
    <main className='min-h-screen'>
      <section className='bg-main text-white py-20'>
        <div className='container mx-auto px-6 text-center'>
          <h1 className='text-5xl font-semibold mb-4'>Terms & Privacy</h1>
          <p className='text-xl max-w-2xl mx-auto'>
            Transparency matters to us. Here&apos;s how we operate and protect your data.
          </p>
        </div>
      </section>

      <section className='bg-white py-16'>
        <div className='container mx-auto px-6 max-w-4xl'>
          <h2 className='text-3xl font-semibold mb-8'>Legal Disclosure</h2>

          <div className='space-y-6 text-gray-700 leading-relaxed'>
            <div>
              <h3 className='text-xl font-semibold mb-2'>Company Information</h3>
              <p>
                miniChef is operated by miniChef SRL, a company registered in Romania.
                All content and services provided on this website are subject to Romanian
                and European Union law.
              </p>
            </div>

            <div>
              <h3 className='text-xl font-semibold mb-2'>Intellectual Property</h3>
              <p>
                All content on miniChef, including but not limited to text, images, logos,
                and AI-generated recipes, is the property of miniChef SRL or its content
                contributors. Unauthorized reproduction, distribution, or modification of
                any materials is prohibited without prior written consent.
              </p>
            </div>

            <div>
              <h3 className='text-xl font-semibold mb-2'>Third-Party Assets</h3>
              <p>
                Social media icons (Facebook, Instagram, X) used on this website are
                provided by <a href='https://www.flaticon.com/' target='_blank' rel='noopener noreferrer' className='text-main font-medium hover:underline'>Flaticon</a>.
              </p>
            </div>

            <div>
              <h3 className='text-xl font-semibold mb-2'>Disclaimer</h3>
              <p>
                The recipes generated by our AI are intended for informational purposes only.
                miniChef does not guarantee the accuracy, completeness, or suitability of any
                recipe for specific dietary needs or restrictions. Users are responsible for
                verifying ingredients, especially regarding allergies and dietary requirements.
              </p>
            </div>

            <div>
              <h3 className='text-xl font-semibold mb-2'>Limitation of Liability</h3>
              <p>
                miniChef shall not be held liable for any direct, indirect, incidental, or
                consequential damages arising from the use of this platform or the
                preparation of meals based on the recipes provided. Use of this service is
                at the user&apos;s own risk.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className='bg-gray-100 py-16'>
        <div className='container mx-auto px-6 max-w-4xl'>
          <h2 className='text-3xl font-semibold mb-8'>Privacy Policy</h2>

          <div className='space-y-6 text-gray-700 leading-relaxed'>
            <div>
              <h3 className='text-xl font-semibold mb-2'>Data We Collect</h3>
              <p>
                When you use miniChef, we may collect the following information:
              </p>
              <ul className='list-disc ml-6 mt-2 space-y-1'>
                <li>Ingredients and search queries you enter</li>
                <li>Account information if you join the community (name, email)</li>
                <li>Usage data such as pages visited and features used</li>
                <li>Device and browser information for analytics purposes</li>
              </ul>
            </div>

            <div>
              <h3 className='text-xl font-semibold mb-2'>How We Use Your Data</h3>
              <p>
                Your data is used exclusively to improve your experience on miniChef:
              </p>
              <ul className='list-disc ml-6 mt-2 space-y-1'>
                <li>To generate personalized recipe suggestions</li>
                <li>To improve our AI models and recipe quality</li>
                <li>To communicate with you about your account or support requests</li>
                <li>To analyze usage patterns and improve the platform</li>
              </ul>
            </div>

            <div>
              <h3 className='text-xl font-semibold mb-2'>Data Protection</h3>
              <p>
                We take your privacy seriously. All personal data is stored securely and
                processed in accordance with the General Data Protection Regulation (GDPR).
                We do not sell, trade, or share your personal information with third parties
                for marketing purposes.
              </p>
            </div>

            <div>
              <h3 className='text-xl font-semibold mb-2'>Cookies</h3>
              <p>
                miniChef uses essential cookies to ensure the website functions correctly.
                We also use analytics cookies to understand how visitors interact with
                the platform. You can manage your cookie preferences through your
                browser settings at any time.
              </p>
            </div>

            <div>
              <h3 className='text-xl font-semibold mb-2'>Your Rights</h3>
              <p>
                Under GDPR, you have the right to access, correct, delete, or export your
                personal data at any time. To exercise any of these rights, please contact
                us at <span className='text-main font-medium'>privacy@minichef.com</span>.
              </p>
            </div>

            <div>
              <h3 className='text-xl font-semibold mb-2'>Changes to This Policy</h3>
              <p>
                We may update this policy from time to time. Any changes will be posted
                on this page with an updated revision date. We encourage you to review
                this page periodically.
              </p>
            </div>
          </div>

          <p className='mt-10 text-sm text-gray-500 text-center'>
            Last updated: May 2026
          </p>
        </div>
      </section>
    </main>
  )
}
